version: '3'
services:
  perception:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/app
      - /dev/bus/usb:/dev/bus/usb  # USB passthrough for RealSense
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1  # RealSense often uses multiple video devices
    group_add:
      - video  # Add container to video group
    privileged: true  # Required for RealSense camera access
    network_mode: host  # Required for display forwarding
    ipc: host  # Shared memory for OpenCV windows
